defaults: 
  - _self_
  - feature_extractor : local_binary_pattern
  - descriptor : histogram
  - similarity: cosine_similarity
  - override hydra/launcher: joblib

database_path: ./data/database
query_path: ./data/queries
top_k: 3
